# Challenge 1

In this challenge you will be working on **pokemons**. You will answer a series of questions in order to practice dataframe calculation, aggregation, and transformation.

![Pokemon](pokemon.jpg)

Follow the instructions below and enter your code.

### Import all required libraries

In [23]:
# import libraries
import pandas as pd
import re

### Import data set

Import data set `Pokemon.csv` from the `your-code` directory of this lab. Read the data into a dataframe called `pokemon`.

*Data set attributed to [Alberto Barradas](https://www.kaggle.com/abcsds/pokemon/)*

In [129]:
# import data set
pokemon=pd.read_csv('C:/Users/Claire/Documents/GitHub/data-labs/module-2/lab-df-calculation-and-transformation/your-code/Pokemon.csv')

### Print first 10 rows of `pokemon`

In [130]:
# enter your code here
pokemon.head(10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False

When you look at a data set, you often wonder what each column means. Some open-source data sets provide descriptions of the data set. In many cases, data descriptions are extremely useful for data analysts to perform work efficiently and successfully.

For the `Pokemon.csv` data set, fortunately, the owner provided descriptions which you can see [here](https://www.kaggle.com/abcsds/pokemon/home). For your convenience, we are including the descriptions below. Read the descriptions and understand what each column means. This knowledge is helpful in your work with the data.

| Column | Description |
| --- | --- |
| # | ID for each pokemon |
| Name | Name of each pokemon |
| Type 1 | Each pokemon has a type, this determines weakness/resistance to attacks |
| Type 2 | Some pokemon are dual type and have 2 |
| Total | A general guide to how strong a pokemon is |
| HP | Hit points, or health, defines how much damage a pokemon can withstand before fainting |
| Attack | The base modifier for normal attacks (eg. Scratch, Punch) |
| Defense | The base damage resistance against normal attacks |
| SP Atk | Special attack, the base modifier for special attacks (e.g. fire blast, bubble beam) |
| SP Def | The base damage resistance against special attacks |
| Speed | Determines which pokemon attacks first each round |
| Generation | Number of generation |
| Legendary | True if Legendary Pokemon False if not |

### Obtain the distinct values across `Type 1` and `Type 2`

Exctract all the values in `Type 1` and `Type 2`. Then create an array containing the distinct values across both fields.

In [131]:
# enter your code here

# pokemon.groupby(['Type 1','Type 2'])['#'].sum()

pokemon[['Type 1', 'Type 2']]
pokemon['Type1_Type2'] = (pokemon['Type 1'] +' '+ pokemon['Type 2'])
pokemon['Type2_Type1'] = (pokemon['Type 2'] +' '+ pokemon['Type 1'])
l1 = pokemon['Type1_Type2'].drop_duplicates().to_list()
l2 = pokemon['Type2_Type1'].drop_duplicates().to_list()
for i in l1:
   if i in l2:
       l1.remove(i)
l1

['Grass Poison',
 'Fire Flying',
 'Bug Flying',
 'Normal Flying',
 'Poison Ground',
 'Normal Fairy',
 'Poison Flying',
 'Bug Grass',
 'Water Fighting',
 'Rock Ground',
 'Water Psychic',
 'Electric Steel',
 'Ghost Poison',
 'Ground Rock',
 'Psychic Fairy',
 'Ice Psychic',
 'Water Flying',
 'Water Dark',
 'Rock Flying',
 'Ice Flying',
 'Electric Flying',
 'Psychic Fighting',
 'Fairy Flying',
 'Psychic Flying',
 'Water Fairy',
 'Grass Flying',
 'Water Ground',
 'Dark Flying',
 'Normal Psychic',
 'Bug Steel',
 'Ground Flying',
 'Bug Rock',
 'Bug Fighting',
 'Dark Ice',
 'Fire Rock',
 'Ice Ground',
 'Steel Flying',
 'Dark Fire',
 'Water Dragon',
 'Rock Dark',
 'Grass Dragon',
 'Fire Fighting',
 'Water Grass',
 'Grass Dark',
 'Bug Water',
 'Grass Fighting',
 'Bug Ground',
 'Bug Ghost',
 'Steel Fairy',
 'Fighting Psychic',
 'Ground Dragon',
 'Dragon Fairy',
 'Rock Psychic',
 'Ground Psychic',
 'Rock Grass',
 'Ice Water',
 'Steel Psychic',
 'Dragon Psychic',
 'Grass Ground',
 'Water Steel',
 'Normal Water',
 'Ghost Flying',
 'Normal Fighting',
 'Poison Dark',
 'Dragon Ground',
 'Poison Bug',
 'Poison Fighting',
 'Grass Ice',
 'Ice Ghost',
 'Electric Ghost',
 'Electric Fire',
 'Electric Ice',
 'Electric Grass',
 'Steel Dragon',
 'Fire Steel',
 'Ghost Dragon',
 'Ground Steel',
 'Grass Fairy',
 'Ground Dark',
 'Dark Fighting',
 'Normal Grass',
 'Water Ghost',
 'Bug Electric',
 'Grass Steel',
 'Ghost Fire',
 'Ground Electric',
 'Ground Ghost',
 'Dark Steel',
 'Dark Dragon',
 'Bug Fire',
 'Rock Fighting',
 'Dragon Electric',
 'Dragon Ice',
 'Normal Ground',
 'Fire Normal',
 'Steel Ghost',
 'Poison Water',
 'Poison Dragon',
 'Electric Normal',
 'Rock Dragon',
 'Rock Ice',
 'Fighting Flying',
 'Electric Fairy',
 'Rock Fairy',
 'Ghost Grass',
 'Psychic Ghost',
 'Fire Water']

### Cleanup `Name` that contain "Mega"

If you have checked out the pokemon names carefully enough, you should have found there are junk texts in the pokemon names which contain "Mega". We want to clean up the pokemon names. For instance, "VenusaurMega Venusaur" should be "Mega Venusaur", and "CharizardMega Charizard X" should be "Mega Charizard X".

In [132]:
# enter your code here
pokemon['Name'] = pokemon['Name'].str.replace("\w*Mega","Mega")

# test transformed data

pokemon.head(10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Type1_Type2,Type2_Type1
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,Grass Poison,Poison Grass
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,Grass Poison,Poison Grass
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,Grass Poison,Poison Grass
3,3,Mega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,Grass Poison,Poison Grass
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,NaN,NaN
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False,NaN,NaN
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False,Fire Flying,Flying Fire
7,6,Mega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False,Fire Dragon,Dragon Fire
8,6,Mega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False,Fire Flying,Flying Fire
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False,NaN,NaN

### Create a new column called `A/D Ratio` whose value equals to `Attack` devided by `Defense`

For instance, if a pokemon has the Attack score 49 and Defense score 49, the corresponding `A/D Ratio` is 49/49=1.

In [133]:
# enter your code here

pokemon['A/D Ratio']=pokemon['Attack']/pokemon['Defense']

### Identify the pokemon with the highest `A/D Ratio`

In [134]:
# enter your code here
pokemon['A/D Ratio'].max()

9.0

### Identify the pokemon with the lowest A/D Ratio

In [135]:
# enter your code here
pokemon['A/D Ratio'].min()

0.043478260869565216

### Create a new column called `Combo Type` whose value combines `Type 1` and `Type 2`.

Rules:

* If both `Type 1` and `Type 2` have valid values, the `Combo Type` value should contain both values in the form of `<Type 1> <Type 2>`. For example, if `Type 1` value is `Grass` and `Type 2` value is `Poison`, `Combo Type` will be `Grass-Poison`.

* If `Type 1` has valid value but `Type 2` is not, `Combo Type` will be the same as `Type 1`. For example, if `Type 1` is `Fire` whereas `Type 2` is `NaN`, `Combo Type` will be `Fire`.

In [136]:
# enter your code here

# if pokemon['Type 1'].isnull==True:
#     pokemon['Combo Type']=pokemon['Type 2']
# elif pokemon['Type 2'].isnull==True:
#     pokemon['Combo Type']=pokemon['Type 1']
# else:
#     pokemon['Combo Type']=pokemon['Type 1']+'-'+pokemon['Type 2']

# pokemon['Combo Type']

pokemon['Type 1'] = pokemon['Type 1'].fillna("-")
pokemon['Type 2'] = pokemon['Type 2'].fillna("-")
pokemon['Combo Type'] = pokemon['Type 1'] + '-' + pokemon['Type 2']
pokemon['Combo Type']
pokemon['Combo Type'] = pokemon['Combo Type'].str.replace('--','')
pokemon['Combo Type']

0         Grass-Poison
1         Grass-Poison
2         Grass-Poison
3         Grass-Poison
4                 Fire
5                 Fire
6          Fire-Flying
7          Fire-Dragon
8          Fire-Flying
9                Water
10               Water
11               Water
12               Water
13                 Bug
14                 Bug
15          Bug-Flying
16          Bug-Poison
17          Bug-Poison
18          Bug-Poison
19          Bug-Poison
20       Normal-Flying
21       Normal-Flying
22       Normal-Flying
23       Normal-Flying
24              Normal
25              Normal
26       Normal-Flying
27       Normal-Flying
28              Poison
29              Poison
            ...
770              Fairy
771    Fighting-Flying
772     Electric-Fairy
773         Rock-Fairy
774             Dragon
775             Dragon
776             Dragon
777        Steel-Fairy
778        Ghost-Grass
779        Ghost-Grass
780        Ghost-Grass
781        Ghost-Grass
782        Ghost-Grass
783        Ghost-Grass
784        Ghost-Grass
785        Ghost-Grass
786        Ghost-Grass
787        Ghost-Grass
788                Ice
789                Ice
790      Flying-Dragon
791      Flying-Dragon
792              Fairy
793        Dark-Flying
794      Dragon-Ground
795         Rock-Fairy
796         Rock-Fairy
797      Psychic-Ghost
798       Psychic-Dark
799         Fire-Water
Name: Combo Type, Length: 800, dtype: object

### Identify the pokemons whose `A/D Ratio` are among the top 5

In [137]:
# enter your code here
pokemon.nlargest(5, ['A/D Ratio'])

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Type1_Type2,Type2_Type1,A/D Ratio,Combo Type
429,386,DeoxysAttack Forme,Psychic,-,600,50,180,20,180,20,150,3,True,NaN,NaN,9.000,Psychic
347,318,Carvanha,Water,Dark,305,45,90,20,65,20,65,3,False,Water Dark,Dark Water,4.500,Water-Dark
19,15,Mega Beedrill,Bug,Poison,495,65,150,40,15,80,145,1,False,Bug Poison,Poison Bug,3.750,Bug-Poison
453,408,Cranidos,Rock,-,350,67,125,40,30,30,58,4,False,NaN,NaN,3.125,Rock
348,319,Sharpedo,Water,Dark,460,70,120,40,95,40,95,3,False,Water Dark,Dark Water,3.000,Water-Dark

### For the 5 pokemons printed above, aggregate `Combo Type` and use a list to store the unique values.

Your end product is a list containing the distinct `Combo Type` values of the 5 pokemons with the highest `A/D Ratio`.

In [138]:
# enter your code here
lst_best_combo=list((set((pokemon.nlargest(5, ['A/D Ratio']))['Combo Type'])))
lst_best_combo

['Rock', 'Bug-Poison', 'Water-Dark', 'Psychic']

### For each of the `Combo Type` values obtained from the previous question, calculate the mean scores of all numeric fields across all pokemons.

Your output should look like below:

![Aggregate](aggregated-mean.png)

In [ ]:
# enter your code here